const rarities = {
    Rare: 79.26,
    Epic: 17.02,
    Legendary: 3.07,
    Mythic: 0.06,
    Universal: 0.0106,
};

const allskins = {
    Rare: [
        "COSMIC // SHAPER",
        "Whitesnake V2",
        "The Hand: Steel",
        "Project: Platinum",
        "Weather Report: Melon",
        "Kazuma Kiryu",
        "FREEDOM // DIVE",
        "D4C: Ruby",
        "Bisento",
        "D4C: Molten",
        "Star Platinum: Emerald",
        "Nocturnus: Burning",
        "Yone: Three Mop Style",
        "Sticky Fingers: Pink",
        "Pre Dressrosa",
        "Gold Experience: Ruby",
        "Locke & Loaded",
        "Star Platinum: Torquoise",
        "Crazy Diamond: Yellow",
        "D4C: Monochrome",
        "Cloud Experience",
        "Golden Chariot",
        "Chainlocked",
        "Reaper: Reaver",
        "Crazy Diamond: Mint",
        "Whitesnake: Palo Alto",
        "Star Platinum: Not Arcade",
        "Whitesnake: All-Star Battle",
        "The Hand: Melon",
        "Crazy Diamond: Ruby",
        "Legacy",
        "Sticky Fingers: Orange",
        "TWHV: Ruby",
        "Reaper: Clockwork",
        "Weather Report: Orchid Steel",
        "Star Spangled Platinum",
        "Yasuo: Jade Cutter",
        "Sticky Fingers: Red",
        "Shadow Dio: OKC",
        "Star Platinum: Yellow",
        "Gold experience: Rosso",
        "Yasuo: Ame no Habakiri",
        "D$C LT: Gilded",
        "Voidtouched Chariot",
        "Shadow The World Requiem: Spirit",
        "Anshen (Time Skip)",
        "King Crimson: Melon",
        "Zou",
        "Yone: Nichirin Cleavers",
        "TWHV: Sapphire",
        "Gold Experience: Lavender",
        "D4C: Golem",
        "Whitesnake: Eyes of Heaven",
        "Keyblade",
        "Killer Queen: Frigid",
        "Crazy Diamond: Grape",
        "VELVET // SHAPER",
        "Star Platinum: Tanzanite",
        "Industrial Queen",
        "The Hand: Dark",
        "The Strongest: Zero",
        "Sticky Fingers: Dark",
        "Weather Report: Coral",
        "Gold Experience: Melon",
        "Yasuo: Zou Zou",
        "The Hand: Light Green",
        "The Hand: Green",
        "Sticky Fingers: Silver",
        "D4C: Patriot",
        "Sticky Fingers: Lime Green",
        "The World: Codex",
        "King Crimson: Toothpaste",
        "Reaper: Burial Blade",
        "Dressrosa",
        "C-Moon (Eyes of Heaven)",
        "Whitesnake: Melon",
        "Gold Experience: Gelo",
        "Anshen (Ruby)",
        "Kiribachi",
        "The Hand: Red",
        "Sticky Fingers: Grape",
        "Solar",
        "Reaper: Blizzard",
        "Gold Experience: Snow",
        "The Hand: Purple",
        "The World: Legacy",
        "Yasuo: Kageuchi",
        "D4C LT: Monochrome",
        "Yasuo: Shinku",
        "Yasuo: Crimson Blade",
        "Wano",
        "Yasuo: Enma",
        "D4C: Mint",
        "C-Moon: Melon",
        "Dying Star",
        "Crazy Diamond: Gilded",
        "Guest",
        "Star Platinum Requiem: Wisp",
        "Cybernetica",
        "Palesnake",
        "STWR: Sunset",
        "Gold Experience Requiem: Melon",
        "D4C: Cyber",
        "Shadow Dio: Sun",
        "Yasuo: Viridescent",
        "Reaper: Obsidian",
        "Weather Report: Golden Wind",
    ],
    Epic: [
        "Via Lactea",
        "Yone: Three Sword Style",
        "Nomad Crimson",
        "Shadow Dio: Crystal",
        "Egghead",
        "Gold Experience: Groot",
        "Ghost Rider",
        "OVA",
        "Yasuo: Master Sword",
        "Moon Knight",
        "Thunder",
        "Star Platinum: Baseball player",
        "Gentleman",
        "Anti-Venom",
        "Dragon Slayer",
        "Shadow Dio: K//Amnesia",
        "Star Platinum: Deimos",
        "Yasuo: Virulent",
        "Buster",
        "Reaper: Nightmare",
        "High Voltage",
        "Lance Of Longinus",
        "Shadow Dio: AMSP",
        "Un-Immortal Sword",
        "Reaper: Shadow",
        "Capn Hook",
        "Fist of the North Star",
        "Nocturnus: Dark Tides",
        "Stone Age",
        "Star Platinum: Lord Oton",
        "Lunatic Gem",
        "Yone: Dual Lightsabers",
        "ROSE-STAR",
        "HYDROGEN-STAR",
        "Sorcerer King",
        "Shadow Dio: Ghost",
        "Heaven Slicer",
        "The One Who Left It All Behind",
        "D4C LT: Molten",
        "Reaper: Gordeau",
        "DELTA Servant",
        "TWHV: 20XX",
        "Reaper: Soul Scythe",
        "Punk Hazard",
        "MK Raiden",
        "Crazy Doctor",
        "24 Hour Cinderella",
        "Granite",
        "Black Sparks",
        "The World: 29",
        "Dawn: Silverlight",
        "Mjolnir",
        "Soft & Wet: All Star",
        "TWHV: Lightmare",
        "Sentinel",
        "Yasuo: Bluesteel Blade",
        "Darksteel Greatsword",
        "King Crimson: Monochrome",
        "Mictlan Queen",
        "Reaper: Gemini",
        "The World: OVA",
        "Enel",
        "Okinawa",
        "Shadow Dio: Scarlet",
        "Yasuo: Murasama",
        "Ice Cream Cone",
        "Shadow Dio: RGB",
        "Reaper: Sickle of Sorrow",
        "Frying Pan",
        "Yone: Raiden",
    ],
    Legendary: [
        "Gundam Platinum",
        "Atlantic Warrior",
        "CHROMA",
        "Gold Experience Requiem: Home Console",
        "Reaper: Kite",
        "Stardust Guardian",
        "The World: Gundam",
        "Luminus",
        "The One Who Destroyed It All",
        "Chroma Team",
        "Archangel",
        "The Eye of the Storm",
        "The Strongest: Decisive Battle",
        "Elucidator & Dark Repulser",
        "Pre Timeskip",
        "Lithium",
        "Ashen",
        "Truffle Warrior",
        "Fork",
        "Hallowed",
        "Manga Kars",
        "TWOH: NU",
        "Shadow Dio: Space Pirate",
        "Made In Rainbows",
        "Shadow Bonnie",
        "Onigashima",
        "Cataclysm",
        "Yasuo: Galaxy Blade",
        "Yasuo: Mistsplitter",
        "Lifeline of Kamurocho",
        "Awakened Star Platinum",
        "Dark Emperor",
        "Reaper: Devil's Knife",
        "Awakened The World",
        "Dawn: Rainslasher",
        "Locke: Dark Knight",
        "Starless Patriot",
        "Reaper: Sapphire",
        "Killer Queen: Bomb Devil",
        "Blessing",
        "Wolverine",
        "Shadow Dio: Reckoner",
        "Enshadowed",
        "Dawn: Willbreaker",
        "Enderman Crimson",
        "Negative Creep",
        "Reaper: Quartz",
        "s t w",
    ],
    Mythic: [
        "Xiao",
        "4D Sword",
        "Frost Knight",
        "2099",
        "Polaris",
        "Alchemist Soldier",
        "The Honored One",
        "The World: Greatest High",
        "Star Platinum: Stone Ocean",
        "Polar",
        "Fallen",
        "Voyager",
        "Star Platinum: Over Heaven",
        "Frozen Hook",
        "Scout",
        "Star Platinum: Arcade",
        "U-Star",
        "Killer Queen: Crazy Explosion Girl",
        "Killer Queen: Hazard",
        "Nova",
        "King Crimson: Discipline",
        "Seele",
        "Igris",
        "Big Q",
        "DR // PUDDEST",
        "Yami",
        "VOXEL // SHAPER",
        "Cursed Diamond",
        "Crazy Diamond: Astra",
        "The World: Arcade",
        "The Virtuoso",
        "Nocturnus: Chainsaw Devil",
        "Pipe",
        "C-Moon: Prophet",
        "Demon Blood Sword",
        "Gold Experience Requiem: Rage",
        "Powerplex",
        "Cucumber",
        "Soul King",
        "V2",
    ],
    Universal: ["Metallix", "Sanji", "Reinhardt", "Blood Lord's Sacred Spear"],
};
